# Generated by Django 2.2.12 on 2020-08-03 06:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedHealthStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Name')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthStatsSerializerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('ageGroup', jsonfield.fields.JSONField(verbose_name='Age Group')),
                ('gender', jsonfield.fields.JSONField(verbose_name='Gender')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeseriesHealthStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='Date')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='Hospital Name')),
                ('code', models.CharField(max_length=15, verbose_name='Hospital Code')),
                ('beds', models.PositiveSmallIntegerField(null=True, verbose_name='Hospital Beds')),
                ('telephone', models.CharField(blank=True, max_length=31, null=True, verbose_name='Hospital Telephone')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Hospital Address')),
                ('type', models.CharField(max_length=127, null=True, verbose_name='Hospital Type')),
                ('lng', models.FloatField(null=True, verbose_name='Longitude')),
                ('lat', models.FloatField(null=True, verbose_name='Latitude')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo')),
                ('in_master_list', models.BooleanField(default=False, verbose_name='In Master List')),
            ],
            options={
                'verbose_name': 'Hospital',
                'db_table': 'hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('image_date', models.DateField(null=True, verbose_name='Image Date')),
                ('image_path', models.CharField(max_length=255, null=True, verbose_name='Image File Path')),
                ('image_name', models.CharField(max_length=255, null=True, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Medical Image',
                'db_table': 'medical_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=31, verbose_name='Region Name')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('zoom', models.FloatField(blank=True, null=True, verbose_name='Zoom Level')),
                ('color', models.CharField(blank=True, max_length=15, null=True, verbose_name='Color')),
                ('rgb', models.CharField(blank=True, max_length=15, null=True, verbose_name='RGB')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Region',
                'db_table': 'region',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='XrayAnalysisFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='Disease Name')),
                ('value', models.FloatField(null=True, verbose_name='Disease Confidence')),
                ('medical_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.MedicalImage')),
            ],
            options={
                'verbose_name': 'X-Ray Analysis Finding',
                'db_table': 'xray_analysis_finding',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('code', models.CharField(max_length=31, verbose_name='Site Code')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Hospital')),
            ],
            options={
                'verbose_name': 'ROBO Site',
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=63, verbose_name='Province Name')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='backend.Region')),
            ],
            options={
                'verbose_name': 'Province',
                'db_table': 'province',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('date_acquired', models.DateField(null=True, verbose_name='Date Acquired')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('identity_no', models.CharField(max_length=31, verbose_name='Gender')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_sure', 'Not Sure')], max_length=15, verbose_name='Gender')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age')),
                ('modality', models.CharField(max_length=255, null=True, verbose_name='Modality')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Site')),
            ],
            options={
                'verbose_name': 'Patient Info',
                'db_table': 'patient_info',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='patient_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PatientInfo'),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Site'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Province'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region'),
        ),
        migrations.CreateModel(
            name='AnalysisSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('threshold', jsonfield.fields.JSONField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Site')),
            ],
            options={
                'verbose_name': 'Analysis Setting',
                'db_table': 'analysis_setting',
                'managed': True,
            },
        ),
    ]
