# Generated by Django 2.2.13 on 2020-08-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailedHealthStatsModel',
        ),
        migrations.DeleteModel(
            name='HealthStatsSerializerModel',
        ),
        migrations.DeleteModel(
            name='TimeseriesHealthStatsModel',
        ),
    ]
