# Generated by Django 2.2.13 on 2020-08-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200811_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorgoal',
            name='drawn_goal_1_img_path',
            field=models.CharField(max_length=127, verbose_name='Drawn Goal 1 Image Path'),
        ),
        migrations.AlterField(
            model_name='actorgoal',
            name='drawn_goal_2_img_path',
            field=models.CharField(max_length=127, verbose_name='Drawn Goal 2 Image Path'),
        ),
        migrations.AlterField(
            model_name='actorgoal',
            name='selected_goal_img_path',
            field=models.CharField(max_length=127, null=True, verbose_name='Selected Goal Image Path'),
        ),
    ]
